export const AI_CARD_GENERATION_ERROR_CODES = [
	"FEATURE_DISABLED",
	"CONFIRMATION_REQUIRED",
	"OPENAI_INPUT_TEXT_MODERATION",
	"OPENAI_INPUT_IMAGE_MODERATION",
	"OPENAI_OUTPUT_MODERATION",
	"OPENAI_MODERATION_UNAVAILABLE",
	"OPENAI_REFUSAL",
	"OPENAI_INCOMPLETE_OUTPUT",
	"OPENAI_OUTPUT_SCHEMA_MISMATCH",
	"OPENAI_PROVIDER_TRANSIENT",
	"OPENAI_PROVIDER_CONFIG",
	"OPENAI_PROVIDER_PERMANENT",
] as const;

export type AiCardGenerationErrorCode = (typeof AI_CARD_GENERATION_ERROR_CODES)[number];

const HTTP_STATUS: Readonly<Record<AiCardGenerationErrorCode, number>> = {
	FEATURE_DISABLED: 404,
	CONFIRMATION_REQUIRED: 400,
	OPENAI_INPUT_TEXT_MODERATION: 422,
	OPENAI_INPUT_IMAGE_MODERATION: 422,
	OPENAI_OUTPUT_MODERATION: 422,
	OPENAI_MODERATION_UNAVAILABLE: 503,
	OPENAI_REFUSAL: 422,
	OPENAI_INCOMPLETE_OUTPUT: 502,
	OPENAI_OUTPUT_SCHEMA_MISMATCH: 502,
	OPENAI_PROVIDER_TRANSIENT: 503,
	OPENAI_PROVIDER_CONFIG: 503,
	OPENAI_PROVIDER_PERMANENT: 502,
};

export class AiCardGenerationError extends Error {
	readonly httpStatus: number;

	constructor(readonly code: AiCardGenerationErrorCode) {
		super(code);
		this.name = "AiCardGenerationError";
		this.httpStatus = HTTP_STATUS[code];
	}
}
